f1_blog/standings/urls.py
from django.urls import path
from .views import DriverStandingsView, submit_race_result, RaceView, TrackResultView

urlpatterns = [
    path('', DriverStandingsView.as_view(), name='driver-standings'),
    path('submit-race-result/', submit_race_result, name='submit-race-result'),
    path('tracks/', RaceView.as_view(), name='tracks'),
    path('track/results/<int:pk>', TrackResultView.as_view(), name='track-result')
]

f1_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('f1_blog.web.urls')),
    path('news/', include('f1_blog.news.urls')),
    path('videos/', include('f1_blog.videos.urls')),
    path('standings/', include('f1_blog.standings.urls')),
    path('merchandise/', include('f1_blog.merchandise.urls')),
    path('api/', include('f1_blog.apis.urls')),
    path('cart/', include('f1_blog.cart.urls')),
    path('orders/', include('f1_blog.orders.urls')),


]

f1_blog/standings/models.py
from django.db import models


class Team(models.Model):
    name = models.CharField(max_length=100)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def calculate_total_points(self):
        total_points = 0
        for driver in self.drivers.all():
            total_points += driver.points
        return total_points


class Driver(models.Model):
    name = models.CharField(max_length=100)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='drivers')
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Race(models.Model):
    title = models.CharField(max_length=100)
    track_length = models.FloatField()
    start_date = models.DateField()
    end_date = models.DateField()
    image = models.ImageField(upload_to='race_layout/')
    flag = models.ImageField(upload_to='race_layout/',
                             blank=True,
                             null=True)

    def __str__(self):
        return self.title


class RaceResult(models.Model):
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
    race = models.ForeignKey(Race, on_delete=models.CASCADE)
    position = models.IntegerField()  # Finishing position
    fastest_lap = models.BooleanField()  # True if the driver had the fastest lap

    def __str__(self):
        return f"{self.driver.name} - Race: {self.race}, Position: {self.position}, Fastest Lap: {self.fastest_lap}"

f1_blog/standings/forms.py
from django import forms
from .models import Race, Driver


class RaceResultForm(forms.Form):
    race = forms.ModelChoiceField(queryset=Race.objects.all(), empty_label=None)
    fastest_lap = forms.ModelChoiceField(queryset=Driver.objects.all(), empty_label=None, label='Driver with Fastest Lap')

    def __init__(self, *args, **kwargs):
        super(RaceResultForm, self).__init__(*args, **kwargs)
        drivers = Driver.objects.all()
        position_choices = [(i, f"-{i}-") for i in range(1, 21)]
        for driver in drivers:
            field_name = f"driver_{driver.id}"
            self.fields[field_name] = forms.ChoiceField(choices=position_choices, widget=forms.Select(attrs={'class': 'position-select'}), required=False)
            self.fields[field_name].label = driver.name  # Set label to driver's name

f1_blog/standings/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import ListView
from django.db import models

from .models import Race, Driver, RaceResult, Team
from .forms import RaceResultForm


class DriverStandingsView(ListView):
    model = Driver
    template_name = 'standings/driver_standings.html'
    context_object_name = 'drivers'

    def get_queryset(self):
        return Driver.objects.order_by('-points')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teams = Team.objects.annotate(total_points=models.Sum('drivers__points')).order_by('-total_points')
        context['teams'] = teams
        return context


def get_points(position):
    points = 0
    if position == 1:
        points = 25
    elif position == 2:
        points = 18
    elif position == 3:
        points = 15
    elif position == 4:
        points = 12
    elif position == 5:
        points = 10
    elif position == 6:
        points = 8
    elif position == 7:
        points = 6
    elif position == 8:
        points = 4
    elif position == 9:
        points = 2
    elif position == 10:
        points = 1
    return points


def submit_race_result(request):
    races = Race.objects.all()
    drivers = Driver.objects.all()
    if request.method == 'POST':
        form = RaceResultForm(request.POST)
        if form.is_valid():
            race = form.cleaned_data['race']
            fastest_lap_owner = form.cleaned_data['fastest_lap']
            for driver in drivers:
                position = form.cleaned_data[f"driver_{driver.id}"]
                if position:
                    driver_position = int(position)
                    driver_result = RaceResult.objects.create(
                        race=race,
                        driver=driver,
                        position=driver_position,
                        fastest_lap=(driver == fastest_lap_owner)
                    )
                    driver.points += get_points(driver_position)
                    if driver == fastest_lap_owner:
                        driver.points += 1
                    driver.save()
            return redirect('driver-standings')
    else:
        form = RaceResultForm()

    context = {
        'form': form,
        'races': races,
        'drivers': drivers
    }

    return render(request, 'standings/submit_race_result.html', context)


class RaceView(ListView):
    model = Race
    template_name = 'standings/races.html'
    context_object_name = 'races'

    def get_past_races(self):
        return Race.objects.filter(end_date__lt=timezone.now()).order_by('-end_date')

    def get_next_race(self):
        return Race.objects.filter(start_date__gte=timezone.now()).order_by('start_date').first()

    def get_other_races(self):
        next_race = self.get_next_race()
        if next_race:
            return Race.objects.exclude(pk=next_race.pk).exclude(end_date__lt=timezone.now()).order_by('start_date')
        else:
            return Race.objects.exclude(end_date__lt=timezone.now()).order_by('start_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['past_races'] = self.get_past_races()
        context['next_race'] = self.get_next_race()
        context['other_races'] = self.get_other_races()
        return context


class TrackResultView(ListView):
    model = RaceResult
    template_name = 'standings/track_result.html'

    def get_race_results(self):
        pk = self.kwargs.get('pk')
        return RaceResult.objects.filter(race_id=pk).order_by('position')

    def get_race(self):
        pk = self.kwargs.get('pk')
        return Race.objects.get(pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['race_results'] = self.get_race_results()
        context['race'] = self.get_race()
        return context

templates/standings/driver_standings.html
{% extends 'base.html' %}

{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-5">
                <h1 class="mb-4">Driver Standings</h1>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead class="thead-dark">
                        <tr>
                            <th>Driver</th>
                            <th>Points</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for driver in drivers %}
                            <tr>
                                <td><strong>{{ driver.name }}</strong> - {{ driver.team.name }}</td>
                                <td>{{ driver.points }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-7">
                <div class="col-md-7">
                    <h2 class="mb-6">Team Standings</h2>
                <br>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="thead-dark">
                            <tr>
                                <th>Team</th>
                                <th>Total Points</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for team in teams %}
                                <tr>
                                    <td>{{ team.name }}</td>
                                    <td>{{ team.total_points }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/standings/races.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
    <br><br>
    <h2 class="text-center">Past Races</h2>
    <br>
        <div class="row">
            {% for race in past_races %}
                <div class="col-md-4 mb-4">
                    <div class="card rounded-3 bg-gradient">
                        <div class="card-body">
                            <div class="text-center fw-bold">Round {{ race.pk }}</div>
                            <div class="d-flex justify-content-between">
                                <div class="text-start">{{ race.start_date|date:"d M" }}
                                    - {{ race.end_date|date:"d M" }}</div>
                                <img src="{{ race.flag.url }}" alt="Flag" class="img-fluid rounded"
                                     style="max-width: 40px;">
                            </div>
                            <hr>
                            <h5 class="card-title">{{ race.title }}</h5>
                            <p class="card-text">Track Length: {{ race.track_length }}</p>
                            <img src="{{ race.image.url }}" class="img-fluid" alt="Race Image">
                        </div>
                        <a class="btn btn-primary" href="{% url 'track-result' pk=race.pk %}">Race results→</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <br><br>
    <h2 class="text-center">Next Race</h2>
    <br>
    <div class="container">
        <div class="card rounded-3 text-bg-info">
            <div class="card-body">
                <div class="text-center fw-bold">Round {{ next_race.pk }}</div>
                <div class="d-flex justify-content-between">
                    <div class="text-start">{{ next_race.start_date|date:"d M" }}
                        - {{ next_race.end_date|date:"d M" }}</div>
                    <img src="{{ next_race.flag.url }}" alt="Flag" class="img-fluid rounded"
                         style="max-width: 40px;">
                </div>
                <hr>
                <h5 class="card-title">{{ next_race.title }}</h5>
                <p class="card-text">Track Length: {{ next_race.track_length }}</p>
                <img src="{{ next_race.image.url }}" class="img-fluid" alt="Race Image">
            </div>
        </div>
    </div>
    <br><br>
    <h2 class="text-center">Races Later On</h2>
    <br>
    <div class="container">
        <div class="row">
            {% for race in other_races %}
                <div class="col-md-4 mb-4">
                    <div class="card rounded-3">
                        <div class="card-body">
                            <div class="text-center fw-bold">Round {{ race.pk }}</div>
                            <div class="d-flex justify-content-between">
                                <div class="text-start">{{ race.start_date|date:"d M" }}
                                    - {{ race.end_date|date:"d M" }}</div>
                                <img src="{{ race.flag.url }}" alt="Flag" class="img-fluid rounded"
                                     style="max-width: 40px;">
                            </div>
                            <hr>
                            <h5 class="card-title">{{ race.title }}</h5>
                            <p class="card-text">Track Length: {{ race.track_length }}</p>
                            <img src="{{ race.image.url }}" class="img-fluid" alt="Race Image">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/standings/submit_race_result.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="mb-4">Submit Race Results</h1>
            <form method="post" action="{% url 'submit-race-result' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_race" class="form-label">Race:</label>
                    {{ form.race }}
                </div>
                <div class="mb-3">
                    <label for="id_fastest_lap" class="form-label">Driver with Fastest Lap:</label>
                    <select name="fastest_lap" id="id_fastest_lap" class="form-select">
                        {% for driver in drivers %}
                            <option value="{{ driver.id }}">{{ driver.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Driver</th>
                            <th>Position</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for field in form %}
                            {% if 'driver_' in field.name %}
                                <tr>
                                    <td>{{ field.label }}</td>
                                    <td>{{ field }}</td>
                                    <td>
                                        {% if field_name == form.fastest_lap.html_name %}
                                            {{ form.fastest_lap }}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/standings/track_result.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="container">
        <br><br>
        <h5 class="card-title">{{ race.title }}</h5>
        <br>
        <div class="card mb-3">
            <img src="{{ race.image.url }}" class="card-img-top" alt="{{ race.title }}" style="max-width: 350px;>
        <div class=" card-body">

            <p class="card-text">{{ race.start_date|date:"d M" }} - {{ race.end_date|date:"d M" }}</p>
            <p class="card-text">Length:{{ race.track_length }} km</p>
            <ol>
                {% for result in race_results %}
                    <li>{{ result.driver.name }}</li>
                {% endfor %}
            </ol>
        </div>
    </div>
{% endblock %}