f1_blog/news/urls.py
from django.urls import path

from f1_blog.news import views

urlpatterns = [
   path('', views.PostListView.as_view(), name='post-index'),
   path('add_post/', views.PostAddView.as_view(), name='add-post'),
   path('details/<int:pk>', views.PostDetailView.as_view(), name='post-details'),
   path('toggle-like/<int:comment_id>/', views.toggle_comment_like, name='toggle-like'),
   path('edit/<int:pk>', views.PostEditView.as_view(), name='post-edit'),
   path('delete/<int:pk>', views.PostDeleteView.as_view(), name='post-delete'),

]

f1_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('f1_blog.web.urls')),
    path('news/', include('f1_blog.news.urls')),
    path('videos/', include('f1_blog.videos.urls')),
    path('standings/', include('f1_blog.standings.urls')),
    path('merchandise/', include('f1_blog.merchandise.urls')),
    path('api/', include('f1_blog.apis.urls')),
    path('cart/', include('f1_blog.cart.urls')),
    path('orders/', include('f1_blog.orders.urls')),


]

f1_blog/news/models.py
from django.db import models
from django.contrib.auth.models import User


def upload_to_news_photos(instance, filename):
    return 'news_photos/{0}/{1}'.format(instance.author.username, filename)


class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to=upload_to_news_photos, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_post_comments', blank=True,)

    def __str__(self):
        return f'Comment by {self.author.username} on {self.post.title}'

    def liked_by_current_user(self, user):
        return user in self.likes.all()

f1_blog/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView

from f1_blog.news.models import Post, PostComment


class PostListView(ListView):
    model = Post
    template_name = 'news/news_list.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related('post_comments')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        last_post = Post.objects.order_by('-created_at').first()
        context['last_post'] = last_post

        next_two_posts = Post.objects.exclude(id=last_post.id).order_by('-created_at')[:3]
        context['next_two_posts'] = next_two_posts

        other_posts = Post.objects.exclude(id__in=[last_post.id] + [post.id for post in next_two_posts]).order_by('-created_at')
        context['other_posts'] = other_posts

        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'news/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context['comments'] = post.post_comments.order_by('-created_at')
        return context

    def post(self, request, *args, **kwargs):
        post_id = kwargs.get('pk')
        text = request.POST.get('text')
        post = get_object_or_404(Post, pk=post_id)
        author = request.user
        comment = PostComment.objects.create(post=post, author=author, text=text)
        data = {
            'author_first_name': author.profile.first_name,
            'text': comment.text
        }
        return JsonResponse(data)


def toggle_comment_like(request, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(PostComment, pk=comment_id)
        user = request.user
        if user in comment.likes.all():
            comment.likes.remove(user)
            liked = False
        else:
            comment.likes.add(user)
            liked = True
        return JsonResponse({'liked': liked, 'likes_count': comment.likes.count()})


class PostAddView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'news/add_news.html'
    fields = ['title', 'content', 'photo']
    permission_required = 'post.add_post'
    login_url = '/accounts/login/'
    success_url = reverse_lazy('post-index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'news/edit_news.html'
    fields = ['title', 'content', 'photo']
    success_url = reverse_lazy('post-index')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'news/delete_news.html'
    success_url = reverse_lazy('post-index')

templates/news/add_news.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="mb-4">Add Post</h1>
                <form action="{% url 'add-post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_title" class="form-label">Title</label>
                        <input type="text" name="title" id="id_title" class="form-control">
                    </div>
                    <div class="mb-3">
                        <label for="id_content" class="form-label">Content</label>
                        <textarea name="content" id="id_content" class="form-control"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="id_photo" class="form-label">Photo</label>
                        <input type="file" name="photo" id="id_photo" class="form-control">
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Add Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/news/delete_news.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete "{{ object.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'post-index' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock %}

templates/news/edit_news.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <h1>Edit Post</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save Changes</button>
    <a href="{% url 'post-index' %}" class="btn btn-secondary">Cancel</a>
  </form>
</div>
{% endblock %}

templates/news/news_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}

    <div class="container">
        <div class="row">
            <h1 style="text-align: center">News List</h1>
            <br>
            <div class="d-flex align-items-stretch"> <!-- Added align-items-stretch class -->
                <a href="{% url 'post-details' pk=last_post.pk %}">
                    <br><br>
                    <div class="card text-bg-dark">

                        <img src="{{ last_post.photo.url }}" class="card-img" alt="Post Photo">

                        <div class="card-img-overlay">
                            <h4 class="card-title">{{ last_post.title }}</h4>
                            <p class="card-text"></p>
                            <p class="card-text"><small>{{ last_post.created_at|humanize_time }}</small></p>

                        </div>

                    </div>
                </a>

                <div class="p-2 flex-shrink-1 flex-grow-1">
                    {% for post in next_two_posts %}
                        <div class="card text-white" style="max-width: 20rem; position: relative;">
                            <a href="{% url 'post-details' pk=post.pk %}">
                                <img src="{{ post.photo.url }}" class="card-img" alt="Post Photo"
                                     style="filter: brightness(80%);">
                                <div class="card-img-overlay">
                                    <div style="position: absolute; bottom: 10px; left: 0; width: 100%;">
                                        <div class="card-title"
                                             style="font-size: 1em; font-weight: bold; color: white; padding-left: 1em; padding-right: 1em;">{{ post.title }}</div>
                                        <div style="width: 100%; height: 1px; background: linear-gradient(to left, rgba(255,255,255,0), rgba(255,0,0,1)); margin-bottom: 10px;"></div>
                                        <div class="card-text"
                                             style="font-size: .5em; color: white; padding-left: 1em;">
                                            {{ post.created_at|humanize_time }}</div>
                                        <div class="card-text"
                                             style="position: absolute; bottom: 0; right: 0; font-size: .5em; color: white; padding-right: 1em;">
                                            Comments: {{ post.post_comments.count }}</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <br>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for post in other_posts %}

                <div class="card">
                    <a href="{% url 'post-details' pk=post.pk %}">
                        <img src="{{ post.photo.url }}" class="card-img-top" alt="{{ post.title }}">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title text-decoration-none">{{ post.title }}</h5>
                        <p class="card-text"></p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <small class="text-body-secondary text-decoration-none">{{ post.created_at|humanize_time }}</small>
                        <small class="text-body-secondary text-decoration-none">Comments: {{ post.post_comments.count }}</small>
                    </div>

                </div>

            {% endfor %}
        </div>
{% endblock %}

templates/news/post_detail.html
{% extends 'base.html' %}
{% load moderator_filter %}
{% load static %}


{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <br><br>
                {% if user|is_moderator_or_admin %}
                    <div>
                        <a href="{% url 'post-edit' post.pk %}" class="btn btn-primary me-2">Edit</a>
                        <a href="{% url 'post-delete' post.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                {% endif %}
                <h1>{{ post.title }}</h1>
                <br><br>

                <img src="{{ post.photo.url }}" alt="Post Photo">
                <br><br>

                <p>{{ post.content }}</p>
                <br><br>

                {% if user.is_authenticated %}
                    <h2>Add a Comment</h2>
                    <form id="comment-form">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <textarea class="form-control" name="text" placeholder="Enter your comment"></textarea>
                            <button class="btn btn-primary" type="submit">Submit Comment</button>
                        </div>
                    </form>
                {% else %}
                    <h2 class="align-content-around"><a href="{% url 'login' %}?next={{ request.path }}"
                                                        class="text-decoration-none text-info">Login to comment</a></h2>
                    <br>
                {% endif %}
                <h2>Comments</h2>
                <div class="comment-section border rounded p-3">
                    <ul id="comment-list" class="list-unstyled">
                        {% if comments %}
                            {% for comment in comments %}
                                <li class="comment-item border rounded p-3 mb-3">
                                    {{ comment.author.profile.first_name }}: {{ comment.text }}
                                    <div class="float-end">
                                        {% if comment.liked_by_current_user %}
                                            <img width="20" class="like-button" src="{% static 'icons/liked.png' %}"
                                                 alt="Liked"
                                                 data-comment-id="{{ comment.id }}" data-initial-state="true">
                                        {% else %}
                                            <img width="20" class="like-button" src="{% static 'icons/not_liked.png' %}"
                                                 alt="Not Liked"
                                                 data-comment-id="{{ comment.id }}" data-initial-state="false">
                                        {% endif %}
                                        <span id="like-count-{{ comment.id }}"
                                              class="ms-2">{{ comment.likes.count }}</span>
                                        likes
                                    </div>
                                </li>
                            {% endfor %}
                        {% else %}
                            <h4>Add First Comment</h4>
                        {% endif %}
                    </ul>

                </div>
            </div>
        </div>
    </div>
    <br><br>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            function updateLikeButtonState($button, liked) {
                if (liked) {
                    $button.attr('src', '{% static 'icons/liked.png' %}');
                    $button.attr('alt', 'Liked');
                } else {
                    $button.attr('src', '{% static 'icons/not_liked.png' %}');
                    $button.attr('alt', 'Not Liked');
                }
            }

            $('.like-button').each(function () {
                var $button = $(this);
                var initialState = $button.data('initial-state');
                updateLikeButtonState($button, initialState);
            });

            $('.like-button').on('click', function (event) {
                event.preventDefault();
                var $button = $(this);
                var commentId = $button.data('comment-id');
                $.ajax({
                    type: 'POST',
                    url: '{% url "toggle-like" 0 %}'.replace('0', commentId),
                    data: {
                        'comment_id': commentId,
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        updateLikeButtonState($button, response.liked);
                        $('#like-count-' + commentId).text(response.likes_count);
                    },
                    error: function (xhr, textStatus, errorThrown) {
                    }
                });
            });

            $('#comment-form').on('submit', function (event) {
                event.preventDefault();
                $.ajax({
                    type: 'POST',
                    url: '{% url "post-details" post.id %}',
                    data: $(this).serialize(),
                    success: function (response) {
                        var newComment = '<li class="comment-item border rounded p-3 mb-3">' +
                            response.author_first_name + ': ' + response.text +
                            '<div class="float-end">' +
                            '<img width="20" class="like-button" src="{% static 'icons/not_liked.png' %}" alt="Not Liked" ' +
                            'data-comment-id="' + response.comment_id + '" data-initial-state="false">' +
                            '<span id="like-count-' + response.comment_id + '" class="ms-2">0</span> likes</div>' +
                            '</li>';

                        $('#comment-list').prepend(newComment);

                        $('#comment-form')[0].reset();

                        var $newButton = $('#comment-list').find('[data-comment-id="' + response.comment_id + '"]');
                        updateLikeButtonState($newButton, false);
                    }
                });
            });
        });
    </script>

{% endblock %}